version: '2'
services:
  data-volume:
    container_name: 'data-volume'
    image: busybox
    volumes: 
      - ./data/www:/var/www
      - ./logs/httpd:/var/log/php7

  httpd:
    container_name: 'httpd'
    image: oshou/docker-centos7-php7:latest
    volumes_from:
      - data-volume
    ports:
      - 9000:9000
